/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentHubRouteImport } from './routes/agent-hub'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AiHemaThreadIdRouteImport } from './routes/ai-hema.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/agent-hub',
  path: '/agent-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHemaThreadIdRoute = AiHemaThreadIdRouteImport.update({
  id: '/ai-hema/$threadId',
  path: '/ai-hema/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/leads': typeof LeadsRoute
  '/logistics': typeof LogisticsRoute
  '/settings': typeof SettingsRoute
  '/ai-hema/$threadId': typeof AiHemaThreadIdRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/leads': typeof LeadsRoute
  '/logistics': typeof LogisticsRoute
  '/settings': typeof SettingsRoute
  '/ai-hema/$threadId': typeof AiHemaThreadIdRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/leads': typeof LeadsRoute
  '/logistics': typeof LogisticsRoute
  '/settings': typeof SettingsRoute
  '/ai-hema/$threadId': typeof AiHemaThreadIdRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-hub'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/finance'
    | '/inbox'
    | '/integrations'
    | '/leads'
    | '/logistics'
    | '/settings'
    | '/ai-hema/$threadId'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-hub'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/finance'
    | '/inbox'
    | '/integrations'
    | '/leads'
    | '/logistics'
    | '/settings'
    | '/ai-hema/$threadId'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/agent-hub'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/finance'
    | '/inbox'
    | '/integrations'
    | '/leads'
    | '/logistics'
    | '/settings'
    | '/ai-hema/$threadId'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentHubRoute: typeof AgentHubRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  FinanceRoute: typeof FinanceRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeadsRoute: typeof LeadsRoute
  LogisticsRoute: typeof LogisticsRoute
  SettingsRoute: typeof SettingsRoute
  AiHemaThreadIdRoute: typeof AiHemaThreadIdRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-hub': {
      id: '/agent-hub'
      path: '/agent-hub'
      fullPath: '/agent-hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hema/$threadId': {
      id: '/ai-hema/$threadId'
      path: '/ai-hema/$threadId'
      fullPath: '/ai-hema/$threadId'
      preLoaderRoute: typeof AiHemaThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentHubRoute: AgentHubRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  FinanceRoute: FinanceRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeadsRoute: LeadsRoute,
  LogisticsRoute: LogisticsRoute,
  SettingsRoute: SettingsRoute,
  AiHemaThreadIdRoute: AiHemaThreadIdRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
